name = "services"
main = "src/worker.ts"
compatibility_date = "2023-07-19"
account_id = "367c5b9e9167fafdf4399c87280e0222"
compatibility_flags = [ "nodejs_compat" ]
keep_bindings = [ "plain_text" ]

[env.dev]
vars = { ENVIRONMENT = "dev" }

[env.staging]
vars = { ENVIRONMENT = "staging" }
routes = [
	{ pattern = "staging.services.kukai.app", custom_domain = true },
	{ pattern = "staging.services.ghostnet.kukai.app", custom_domain = true }
]

[env.production]
vars = { ENVIRONMENT = "production" }
routes = [
	{ pattern = "services.kukai.app", custom_domain = true },
	{ pattern = "services.ghostnet.kukai.app", custom_domain = true }
]