name = "services"
main = "src/worker.ts"
compatibility_date = "2023-07-19"

[env.dev]
vars = { ENVIRONMENT = "dev" }

[env.staging]
vars = { ENVIRONMENT = "staging" }
routes = [
	{ pattern = "staging.services.kukai.app", custom_domain = true }
]

[env.production]
vars = { ENVIRONMENT = "production" }
routes = [
	{ pattern = "services.kukai.app", custom_domain = true }
]