name = "services"
main = "src/worker.ts"
compatibility_date = "2023-07-19"
account_id = "367c5b9e9167fafdf4399c87280e0222"
compatibility_flags = [ "nodejs_compat" ]


[env.dev]
vars = { ENVIRONMENT = "dev" }
kv_namespaces = [
	{ binding = "EVENTS", id = "21597de8ef20463ab9b2ac167a4f3553", preview_id = "262be040e83142458669f91cfe130e75" }
]

[env.staging]
vars = { ENVIRONMENT = "staging" }
routes = [
	{ pattern = "staging.services.kukai.app", custom_domain = true },
	{ pattern = "staging.services.ghostnet.kukai.app", custom_domain = true }
]
kv_namespaces = [
	{ binding = "EVENTS", id = "21597de8ef20463ab9b2ac167a4f3553", preview_id = "262be040e83142458669f91cfe130e75" }
]

[env.production]
vars = { ENVIRONMENT = "production" }
routes = [
	{ pattern = "services.kukai.app", custom_domain = true },
	{ pattern = "services.ghostnet.kukai.app", custom_domain = true }
]
kv_namespaces = [
	{ binding = "EVENTS", id = "21597de8ef20463ab9b2ac167a4f3553", preview_id = "262be040e83142458669f91cfe130e75" }
]